# Generated by Django 6.0 on 2025-12-06 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concorrente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome da empresa concorrente', max_length=200, verbose_name='Nome do Concorrente')),
                ('site', models.URLField(blank=True, help_text='Website do concorrente', null=True, verbose_name='Site')),
                ('observacoes', models.TextField(blank=True, help_text='Análise e observações sobre o concorrente', null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concorrentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concorrente',
                'verbose_name_plural': 'Concorrentes',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
