# Generated by Django 6.0 on 2025-12-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concorrentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concorrente',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail de contato', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo', null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
