# Generated by Django 6.0 on 2025-12-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concorrentes', '0002_concorrente_email_concorrente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concorrente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='pontos_fortes',
            field=models.TextField(blank=True, null=True, verbose_name='Pontos Fortes'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='pontos_fracos',
            field=models.TextField(blank=True, null=True, verbose_name='Pontos Fracos'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='responsavel',
            field=models.CharField(blank=True, help_text='Pessoa de contato ou responsável', max_length=200, null=True, verbose_name='Responsável'),
        ),
    ]
