# Generated by Django 6.0 on 2025-12-06 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo ou razão social do cliente', max_length=200, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(help_text='E-mail de contato do cliente', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve estar no formato: "+999999999". Até 15 dígitos permitidos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('empresa', models.CharField(blank=True, help_text='Nome da empresa do cliente', max_length=200, null=True, verbose_name='Empresa')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente'), ('suspenso', 'Suspenso')], default='ativo', help_text='Status atual do cliente', max_length=20, verbose_name='Status')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo do cliente', null=True, verbose_name='Endereço')),
                ('cnpj_cpf', models.CharField(blank=True, help_text='CNPJ ou CPF do cliente', max_length=18, null=True, verbose_name='CNPJ/CPF')),
                ('observacoes', models.TextField(blank=True, help_text='Observações e notas sobre o cliente', null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_cadastro'],
                'indexes': [models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['status'], name='clientes_cl_status_b31356_idx'), models.Index(fields=['-data_cadastro'], name='clientes_cl_data_ca_dcbe85_idx')],
            },
        ),
    ]
