# Generated by Django 6.0 on 2025-12-06 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do lead', max_length=200, verbose_name='Nome do Lead')),
                ('email', models.EmailField(help_text='E-mail de contato do lead', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve estar no formato: "+999999999". Até 15 dígitos permitidos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('origem', models.CharField(choices=[('site', 'Site'), ('indicacao', 'Indicação'), ('redes_sociais', 'Redes Sociais'), ('email', 'E-mail Marketing'), ('telefone', 'Telefone'), ('evento', 'Evento'), ('outro', 'Outro')], default='site', help_text='Canal de origem do lead', max_length=20, verbose_name='Origem')),
                ('interesse', models.CharField(blank=True, help_text='Produto ou serviço de interesse do lead', max_length=200, null=True, verbose_name='Interesse')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('qualificado', 'Qualificado'), ('em_negociacao', 'Em Negociação'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', help_text='Status atual do lead no funil de vendas', max_length=20, verbose_name='Status')),
                ('empresa', models.CharField(blank=True, help_text='Nome da empresa do lead', max_length=200, null=True, verbose_name='Empresa')),
                ('cargo', models.CharField(blank=True, help_text='Cargo do lead na empresa', max_length=100, null=True, verbose_name='Cargo')),
                ('observacoes', models.TextField(blank=True, help_text='Observações e notas sobre o lead', null=True, verbose_name='Observações')),
                ('pontuacao', models.IntegerField(default=0, help_text='Score do lead para qualificação', verbose_name='Pontuação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_ultimo_contato', models.DateTimeField(blank=True, help_text='Data do último contato realizado com o lead', null=True, verbose_name='Último Contato')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_cadastro'],
                'indexes': [models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['origem'], name='leads_lead_origem_1423e3_idx'), models.Index(fields=['-data_cadastro'], name='leads_lead_data_ca_2dcfaf_idx'), models.Index(fields=['-pontuacao'], name='leads_lead_pontuac_5051fe_idx')],
            },
        ),
    ]
