# Generated by Django 6.0 on 2025-12-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
